ALTER TABLE aero.users ADD COLUMN usr_country VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE aero.users ADD COLUMN usr_city VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE aero.users ADD COLUMN usr_is_male BOOLEAN DEFAULT TRUE;